{
 "title": "HTTP Metrics OpenTelemetry",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "route",
    "query": {
     "query": "label_values(http_server_duration_milliseconds_count,http_route)"
    }
   },
   {
    "name": "http_method",
    "query": {
     "query": "label_values(http_server_duration_milliseconds_count,http_method)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "1m,2m,5m,10m,30m" }
  ]
 },
 "panels": [
  {
   "title": "Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(rate(http_server_duration_milliseconds_sum{http_route=~\"${route}\", http_method=~\"${http_method}\"}[$interval])) by (http_route, http_method) /\navg(rate(http_server_duration_milliseconds_count{http_route=~\"${route}\", http_method=~\"${http_method}\"}[$interval])) by (http_route, http_method)",
     "legendFormat": "{{http_method}} {{http_route}}"
    }
   ]
  },
  {
   "title": "Top Requests Count",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 14, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{http_route=~\"${route}\", http_method=~\"${http_method}\"}[$interval])) by (agent, http_route, http_method)",
     "legendFormat": "{{http_method}} {{http_route}}"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "(sum(rate(http_server_duration_milliseconds_count{http_route=~\"${route}\", http_method=~\"${http_method}\"}[$interval])) by (agent, http_route, http_method))",
     "legendFormat": "{{http_method}} {{http_route}}"
    }
   ]
  },
  {
   "title": "Requests statistics",
   "type": "table",
   "gridPos": { "h": 16, "w": 14, "x": 10, "y": 11 },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{http_route=~\"${route}\", http_method=~\"${http_method}\"}[$interval])) by (agent, http_method, http_route)",
     "legendFormat": "x"
    },
    {
     "expr": "sum(increase(http_server_duration_milliseconds_count{ttp_route=~\"${route}\", http_method=~\"${http_method}\", http_status_code=~\"2..\"}[$interval])) by (agent, http_method, http_route)",
     "legendFormat": "x"
    },
    {
     "expr": "sum(increase(http_server_duration_milliseconds_count{http_route=~\"${route}\", http_method=~\"${http_method}\", http_status_code=~\"3..\"}[$interval])) by (agent, http_method, http_route)",
     "legendFormat": "x"
    },
    {
     "expr": "sum(increase(http_server_duration_milliseconds_count{http_route=~\"${route}\", http_method=~\"${http_method}\", http_status_code=~\"4..\"}[$interval])) by (agent, http_method, http_route)",
     "legendFormat": "x"
    },
    {
     "expr": "sum(increase(http_server_duration_milliseconds_count{http_route=~\"${route}\", http_method=~\"${http_method}\", http_status_code=~\"5..\"}[$interval])) by (agent, http_method, http_route)",
     "legendFormat": "x"
    },
    {
     "expr": "sum(rate(http_server_duration_milliseconds_sum{http_route=~\"${route}\", http_method=~\"${http_method}\"}[$interval])) by (agent, http_method, http_route)",
     "legendFormat": "x"
    },
    {
     "expr": "(sum(rate(http_server_duration_milliseconds_sum{http_route=~\"${route}\", http_method=~\"${http_method}\"}[$interval])) by(agent, http_method, http_route) / sum(rate(http_server_duration_milliseconds_count{http_route=~\"${route}\", http_method=~\"${http_method}\"}[$interval])) by(agent, http_method, http_route) >= 0) OR on() vector(0)",
     "legendFormat": "x"
    }
   ]
  },
  {
   "title": "Total Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(increase(http_server_duration_milliseconds_count{job=~\"${Job}\", path=~\"${route}\", method=~\"${http_method}\", status_code=~\"4xx|5xx\"}[$interval])) by (agent, job, path, method)",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  }
 ]
}