---
helmDefaults:
  createNamespace: true
  historyMax: 5

environments:
  default:
    values:
      - environments/default/values.yaml
    kubeContext: kind-workshop


repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: bedag
    url: https://bedag.github.io/helm-charts/

---
releases:
  - name: lgtm
    namespace: monitoring
    chart: grafana/lgtm-distributed
    version: 1.0.1
    condition: lgtm.enabled
    values:
      - values/lgtm.yaml

  - name: grafana-agent-metrics
    namespace: monitoring
    chart: grafana/grafana-agent
    version: 0.31.1
    condition: grafanaAgent.enabled
    values:
      - values/grafana-agent-metrics.yaml

  - name: grafana-agent-logs
    namespace: monitoring
    chart: grafana/grafana-agent
    version: 0.31.1
    condition: grafanaAgent.enabled
    values:
      - values/grafana-agent-logs.yaml
