---
helmDefaults:
  createNamespace: true
  historyMax: 5

environments:
  default:
    values:
      - environments/default/values.yaml
    kubeContext: kind-workshop


repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: bedag
    url: https://bedag.github.io/helm-charts/
  - name: opentelemetry-helm
    url: https://open-telemetry.github.io/opentelemetry-helm-charts
  - name: stakater
    url: https://stakater.github.io/stakater-charts
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx

---
releases:
  - name: ingress-nginx
    labels:
      component: base
    namespace: default
    version: 4.10.0
    chart: ingress-nginx/ingress-nginx
    condition: ingress.enabled
    values:
      - values/nginx.yaml

  - name: lgtm
    labels:
      component: lgtm
    namespace: monitoring
    chart: grafana/lgtm-distributed
    version: 1.0.1
    condition: lgtm.enabled
    values:
      - values/lgtm.yaml

  - name: http-dashboard
    labels:
      component: lgtm
    namespace: monitoring
    chart: bedag/raw
    version: 2.0.0
    condition: lgtm.enabled
    values:
      - values/http-dashboard.yaml

  - name: db-dashboard
    labels:
      component: lgtm
    namespace: monitoring
    chart: bedag/raw
    version: 2.0.0
    condition: lgtm.enabled
    values:
      - values/db-dashboard.yaml

  - name: jvm-dashboard
    labels:
      component: lgtm
    namespace: monitoring
    chart: bedag/raw
    version: 2.0.0
    condition: lgtm.enabled
    values:
      - values/jvm-dashboard.yaml


  - name: opentelemetry-operator
    labels:
      component: otel-operator
    namespace: monitoring
    chart: opentelemetry-helm/opentelemetry-operator
    version: 0.49.0
    condition: otel.enabled
    values:
      - values/otel-operator.yaml

  - name: opentelemetry-instrumentation
    labels:
      component: otel-instrumentation
    namespace: monitoring
    chart: bedag/raw
    version: 2.0.0
    condition: otel.enabled
    values:
      - values/otel-instrumentation.yaml

  - name: sample-springboot
    labels:
      component: apps
    namespace: apps
    chart: stakater/application
    version: 2.3.2
    condition: apps.enabled
    values:
      - values/app-springboot.yaml

  - name: sample-flask
    labels:
      component: apps
    namespace: apps
    chart: stakater/application
    version: 2.3.2
    condition: apps.enabled
    values:
      - values/app-flask.yaml
